disabled_rules: 
  - colon
  - comma
  - control_statement
opt_in_rules: 
  - empty_count
excluded: 
  - Carthage
  - Pods
  - vendor
  - DemoSurveyTests
analyzer_rules: 
  - explicit_self
force_cast: warning
force_try:
  severity: warning 
line_length: 200
type_body_length:
  - 300 
  - 400 
file_length:
  warning: 500
  error: 1200
type_name:
  min_length: 1
  max_length: 
    warning: 40
    error: 50
  excluded: iPhone 
identifier_name:
  min_length: 1
nesting:
  type_level: 3
reporter: "xcode" 