before_install:
    - gem update --system
    - gem install bundler
    - bundle install
    - bundle exec pod install --repo-update
    - gem install linterbot
    - brew install swiftlint
cache:
  - bundler
  - cocoapods
language: objective-c
osx_image: xcode10
xcode_project: DemoSurvey.xcworkspace
xcode_scheme: DemoSurveyTests
xcode_destination: platform=iOS Simulator,OS=10.0,name=iPhone 8
script:
    - ./scripts/lint
    - xcodebuild clean build -sdk iphonesimulator -workspace DemoSurvey.xcworkspace -scheme DemoSurveyTests CODE_SIGNING_REQUIRED=NO
install:
    - sudo systemsetup -settimezone Asia/Ho_Chi_Minh